### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Chengyi-Hua** [Chengyi-Hua/Web-Programming-project#4]
kann nun die Webapp aufrufen (Siehe Readme für Setuphilfe etc) jedoch gibt es noch Probleme. dann die Rückgabe aus Backend nicht mehr kommen. Wisst ihr noch wie genau wir da vorgegangen sind? Ich meine Code-Basis ist das  gleiche, gab es Befehle in der Terminal, die ich verpasst habe?

**Comment by yassdenn** [comment]
denn run --allow-all server.ts
